name: Build MaD Firmware

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio
    - name: Install propeller platformio platform
      run: pio pkg install --platform https://github.com/RileyMcCarthy/platform-propeller.git
    - name: Build Platformio project
      run: pio run -e propeller2
    - uses: actions/upload-artifact@v3
      with:
        name: MaD-Firmware-${{ github.run_number }}.bin
        path: .pio/build/propeller2/program
