name: Build MaD Firmware

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio
    - name: Install propeller platformio platform
      run: pio pkg install --platform https://github.com/RileyMcCarthy/platform-propeller.git
    - name: Extract version from tag
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          # If building from a tag, extract the version number
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version from tag: $VERSION"
        else
          # Default version for non-tag builds
          echo "VERSION=dev" >> $GITHUB_OUTPUT
          echo "Using default version: dev"
        fi
    - name: Build Platformio project
      run: pio run -e propeller2 --build-flags="-DFIRMWARE_VERSION=\"${{ steps.get_version.outputs.VERSION }}\""
    - name: Copy and rename build artifact
      run: |
        mkdir -p release-assets
        cp .pio/build/propeller2/program release-assets/program
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: MaD-Firmware-${{ github.run_number }}
        path: release-assets/program

  create-release:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Display structure of downloaded files
        run: ls -R artifacts
          
      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Copy program to release folder
        run: |
          mkdir -p release
          cp artifacts/MaD-Firmware-*/program release/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: MaD Firmware ${{ steps.get_version.outputs.VERSION }}
          files: release/program
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
